name: Claude Code Review

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write 

on:
  pull_request:
    types: [opened] # PR作成時に実行

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      # git diff操作を可能にするためにコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 正確な差分のために完全な履歴を取得

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - name: Run Code Review with Claude
        id: code-review
        uses: anthropics/claude-code-action@beta
        with:
          trigger_phrase: ""
          timeout_minutes: "60"
          github_token: ${{ steps.app-token.outputs.token }}
          use_bedrock: "true"
          anthropic_model: "apac.anthropic.claude-sonnet-4-20250514-v1:0"
          # レビューの焦点領域を定義
          custom_instructions: "Please think thoughts in English. PR変更をレビューしてください。コード品質、潜在的なバグ、パフォーマンスの問題に焦点を当ててください。適切な改善点を提案してください。必ず日本語で応対して。"
        env:
          ANTHROPIC_BEDROCK_BASE_URL: "https://bedrock-runtime.ap-northeast-1.amazonaws.com"